# see https://yarnpkg.com/configuration/yarnrc
nodeLinker: node-modules

npmAlwaysAuth: true

npmAuthToken: "${NPM_TOKEN}"

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistryServer: "https://repo.huaweicloud.com/repository/npm/"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
